### ISSUE TITLE
No recorded video file 

### ISSUE THREAD

**Issue by patolax** [z4hyoung/ViewRecorder#2]
I ran this project on my device, manually enabled all permissions. 

Although it says 'stopRecord successfully!', I could not find any file in '\data\com.z4hyoung.viewrecorderdemo\cache'. I tried changing the location still no luck. Any ideas as to how to get it to work?

By any chance do you know a way to record a surfaceview? maybe another recommended technique you would use for that task.

**Comment by z4hyoung** [comment]
Could you check video file at '**/data/data**/com.z4hyoung.viewrecorderdemo/cache' please?
I don't find a way to record a SurfaceView, have you checked MediaProjection? It can be used to capture whole screen.
